# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05700cfb0fde30bdb21587f08a5624443f8c5163cf6a0ca40b9595ea4e613851236f37fba95ab9206303dd0eb64b9e7ef04b9287357fe05d98f9a429f43dbf8f

test:
  secret_key_base: 7fdfaf03f7da799b440c31ef5920a55e84d206a04a77bd63ccff3f7193a886ac40cfcca77b2b248bb109572f95a85d33a972f12ed770a01c7aff2890b71583a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
